"""fix price_at_order typo

Revision ID: 5486cfaa952b
Revises: 4da53db40d3e
Create Date: 2026-05-02 17:57:20.844072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5486cfaa952b'
down_revision: Union[str, Sequence[str], None] = '4da53db40d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_items",
        "price_ar_order",
        new_column_name="price_at_order"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_items",
        "price_at_order",
        new_column_name="price_ar_order"
    )
    # ### end Alembic commands ###
