name: CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/online-cinema
            git fetch origin develop
            git reset --hard origin/develop
            docker compose up -d --build --remove-orphans
            docker compose exec -T web alembic upgrade head
            docker compose ps
