name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: online_cinema_test
          POSTGRES_USER: cinema_test_user
          POSTGRES_PASSWORD: cinema_test_password
        ports:
          - 5434:5432

      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      ENV: test
      ASYNC_DATABASE_URL: postgresql+asyncpg://cinema_test_user:cinema_test_password@localhost:5434/online_cinema_test
      SYNC_DATABASE_URL: postgresql+psycopg2://cinema_test_user:cinema_test_password@localhost:5434/online_cinema_test

      JWT_SECRET_KEY: test_secret_key
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7

      CELERY_BROKER_URL: redis://localhost:6379/0
      CELERY_RESULT_BACKEND: redis://localhost:6379/0

      SMTP_HOST: localhost
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      EMAIL_FROM: noreply@test.local

      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      S3_ENDPOINT_URL: http://localhost:9000
      S3_PUBLIC_ENDPOINT_URL: http://127.0.0.1:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET_NAME: online-cinema-test
      S3_REGION: us-east-1

      STRIPE_SECRET_KEY: sk_test_dummy
      STRIPE_WEBHOOK_SECRET: whsec_dummy

      BACKEND_URL: http://test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install "poetry==2.2.1"

      - name: Regenerate lock in CI
        run: poetry lock

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run migrations
        run: poetry run alembic upgrade head

      - name: Run tests
        run: poetry run pytest
